<?php

/**
 * Product richsnippets template
 *
 * @var $block \Nakrani\Richsnippets\Block\Richsnippets\Product
 */

$currentProduct = $block->getCurrentProduct();
$productImageUrl = $block->getImageUrl($currentProduct);
$productDescription = $block->getProductDescription($currentProduct);
$rattingCount = $block->getRatingCount();
$reviewCount = $block->getReviewSummary();
$currencyCode = $block->getCurrencyCode();
$specialPriceToDate = $block->changeDateFormat($currentProduct->getSpecialToDate());
$isModuleStatus = $this->helper('Nakrani\Richsnippets\Helper\Data')->getConfig('richsnippets/general/enable');
$isProductSnippetsEnable = $this->helper('Nakrani\Richsnippets\Helper\Data')->getConfig('richsnippets/general/productsnippets');
?>
<?php if ($isModuleStatus && $isProductSnippetsEnable) : ?>
  <div>
    <div itemtype="http://schema.org/Product" itemscope>
      <meta itemprop="mpn" content="925872" />
      <meta itemprop="name" content="<?php echo $block->escapeHtml($currentProduct->getName()); ?>" />
      <link itemprop="image" href="<?php echo $productImageUrl; ?>" />
      <meta itemprop="description" content="<?php echo $block->escapeHtml($productDescription); ?>" />
      <div itemprop="offers" itemtype="http://schema.org/Offer" itemscope>
        <link itemprop="url" href="<?php echo $block->escapeHtml($currentProduct->getproductUrl()); ?>" />
        <?php if ($currentProduct->getQty() > 0) : ?> 
        <meta itemprop="availability" content="https://schema.org/InStock" />
      <?php else : ?>
        <meta itemprop="availability" content="https://schema.org/OutOfStock" />
      <?php endif; ?>
        <meta itemprop="priceCurrency" content="<?php echo $block->escapeHtml($currencyCode); ?>" />
        <meta itemprop="itemCondition" content="https://schema.org/UsedCondition" />
        <meta itemprop="price" content="<?php echo $block->escapeHtml($currentProduct->getFinalPrice()); ?>" />
        <meta itemprop="priceValidUntil" content="<?php echo $block->escapeHtml($specialPriceToDate); ?>" />
       <!--  <div itemprop="seller" itemtype="http://schema.org/Organization" itemscope>
          <meta itemprop="name" content="Executive Objects" />
        </div> -->
      </div>
      <div itemprop="aggregateRating" itemtype="http://schema.org/AggregateRating" itemscope>
        <meta itemprop="reviewCount" content="<?php echo $block->escapeHtml($reviewCount); ?>" />
        <meta itemprop="ratingValue" content="<?php echo $block->escapeHtml($rattingCount); ?>" />
      </div>
      <div itemprop="review" itemtype="http://schema.org/Review" itemscope>
        <div itemprop="author" itemtype="http://schema.org/Person" itemscope>
          <meta itemprop="name" content=" " />
        </div>
        <div itemprop="reviewRating" itemtype="http://schema.org/Rating" itemscope>
          <meta itemprop="ratingValue" content="4" />
          <meta itemprop="bestRating" content="5" />
        </div>
      </div>
      <meta itemprop="sku" content="<?php echo $block->escapeHtml($currentProduct->getSku()); ?>" />
      <!-- <div itemprop="brand" itemtype="http://schema.org/Thing" itemscope>
        <meta itemprop="name" content="ACME" />
      </div> -->
    </div>
  </div>
<?php endif; ?>   
